<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Sunday, March 31, 2024 7:56:35 PM</msg><msg code="0" type="0">
 1. Creating outputs
</msg><msg code="0" type="0">    - Spans</msg><msg code="0" type="0">testing</msg><msg code="0" type="0">&lt;geoprocessing spatial reference object object at 0x000001D631D3BB30&gt;</msg><msg code="0" type="0">    - Structures</msg><msg code="0" type="0">    - Sections</msg><msg code="-2147467259" type="100">Traceback (most recent call last):
  File "D:\working\xml_to_layer.py", line 222, in &lt;module&gt;
    main()
  File "D:\working\xml_to_layer.py", line 195, in main
    pls_cadd_list = pls_cadd_comparison_table(xml_file)
  File "D:\working\xml_to_layer.py", line 108, in pls_cadd_comparison_table
    for row in cursor:
RuntimeError: Cannot find field 'SAP_FUNC_L'
</msg><msg code="0" type="0">Failed script Script...</msg><msg code="-2147467259" type="100">Failed to execute (Script).</msg><msg code="0" type="3">Failed at Sunday, March 31, 2024 7:56:46 PM (Elapsed Time: 10.96 seconds)</msg></messages>