<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Monday, April 1, 2024 8:54:58 AM</msg><msg code="0" type="0">
 1. Creating outputs
</msg><msg code="0" type="0">    - Spans</msg><msg code="0" type="0">testing</msg><msg code="0" type="0">&lt;geoprocessing spatial reference object object at 0x000001D630C781B0&gt;</msg><msg code="0" type="0">    - Structures</msg><msg code="0" type="0">    - Sections</msg><msg code="0" type="0">['sec_no', 'cable_file_name', 'from_str', 'to_str', 'best_match', 'arc_wire_type', 'arc_from_str', 'arc_to_str']</msg><msg code="-2147467259" type="100">Traceback (most recent call last):
  File "D:\working\xml_to_layer.py", line 216, in &lt;module&gt;
    main()
  File "D:\working\xml_to_layer.py", line 210, in main
    for row in cursor:
RuntimeError: Cannot find field 'sec_no'
</msg><msg code="0" type="0">Failed script Script...</msg><msg code="-2147467259" type="100">Failed to execute (Script).</msg><msg code="0" type="3">Failed at Monday, April 1, 2024 8:55:19 AM (Elapsed Time: 21.52 seconds)</msg></messages>